project_id = "wjzqolnmdqmmcxejmunn"

[functions.evolution-create-instance]
verify_jwt = false

[functions.evolution-connect]
verify_jwt = false

[functions.evolution-connection-status]
verify_jwt = false

[functions.evolution-disconnect]
verify_jwt = false

[functions.evolution-set-webhook]
verify_jwt = false

[functions.enviar-mensagem]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.evolution-fetch-messages]
verify_jwt = false

[functions.download-media]
verify_jwt = false

[functions.ai-responder]
verify_jwt = false

[functions.executar-acao]
verify_jwt = false

[functions.transferir-atendimento]
verify_jwt = false

[functions.resumir-conversa]
verify_jwt = false

[functions.transcrever-audio]
verify_jwt = false
